config/routes.rb
Rails.application.routes.draw do
  resources :jus
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ju.rb
class Ju < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jus_controller.rb
class JusController < ApplicationController
  before_action :set_ju, only: [:show, :edit, :update, :destroy]

  # GET /jus
  # GET /jus.json
  def index
    @jus = Ju.all
  end

  # GET /jus/1
  # GET /jus/1.json
  def show
  end

  # GET /jus/new
  def new
    @ju = Ju.new
  end

  # GET /jus/1/edit
  def edit
  end

  # POST /jus
  # POST /jus.json
  def create
    @ju = Ju.new(ju_params)

    respond_to do |format|
      if @ju.save
        format.html { redirect_to @ju, notice: 'Ju was successfully created.' }
        format.json { render :show, status: :created, location: @ju }
      else
        format.html { render :new }
        format.json { render json: @ju.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jus/1
  # PATCH/PUT /jus/1.json
  def update
    respond_to do |format|
      if @ju.update(ju_params)
        format.html { redirect_to @ju, notice: 'Ju was successfully updated.' }
        format.json { render :show, status: :ok, location: @ju }
      else
        format.html { render :edit }
        format.json { render json: @ju.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jus/1
  # DELETE /jus/1.json
  def destroy
    @ju.destroy
    respond_to do |format|
      format.html { redirect_to jus_url, notice: 'Ju was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ju
      @ju = Ju.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ju_params
      params.fetch(:ju, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jus_helper.rb
module JusHelper
end

app/views/jus/_form.html.erb
<%= form_for(ju) do |f| %>
  <% if ju.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ju.errors.count, "error") %> prohibited this ju from being saved:</h2>

      <ul>
      <% ju.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jus/edit.html.erb
<h1>Editing Ju</h1>

<%= render 'form', ju: @ju %>

<%= link_to 'Show', @ju %> |
<%= link_to 'Back', jus_path %>

app/views/jus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jus</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jus.each do |ju| %>
      <tr>
        <td><%= link_to 'Show', ju %></td>
        <td><%= link_to 'Edit', edit_ju_path(ju) %></td>
        <td><%= link_to 'Destroy', ju, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ju', new_ju_path %>

app/views/jus/new.html.erb
<h1>New Ju</h1>

<%= render 'form', ju: @ju %>

<%= link_to 'Back', jus_path %>

app/views/jus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ju_path(@ju) %> |
<%= link_to 'Back', jus_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Juju</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>